server:
  port: 8881 # ${port:8881}


xxl:
  job:
    admin:
      addresses: http://192.168.200.130:8888/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample # xxl-job-sharding-executor
      port: 9999 # ${executor.port:9999}